config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:index]
  resources :imports, only: [:index, :show, :new, :create] do
    member do
      post :assign
      get :execute
    end
  end
  devise_for :users
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:index]
      resources :imports, only: [:index, :show]
      post :sign_up, to: 'auth#sign_up'
      post :sign_in, to: 'auth#sign_in'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/credit_card_validable.rb
module CreditCardValidable
  extend ActiveSupport::Concern

  included do
    before_validation :fetch_franchise
    before_create :mask_number
  end

  private

  def fetch_franchise
    self.franchise = CreditCardValidation.new(number).fetch_issuer_name
  rescue StandardError => e
    errors.add(:credit_card_number, "has #{e.message}")
  end

  def mask_number
    new_number = ('*' * (number.size - 4)) + CreditCardValidation.new(number).last_digits
    self.token = CreditCardValidation.new(number).encrypt
    self.number = new_number
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :credit_card, optional: true, dependent: :destroy

  validates :name, presence: true, format: { with: /\A[a-zA-Z\-\ ]*\z/ }
  validates :email, presence: true, uniqueness: { scope: :user_id }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :birthdate, presence: true
  validates :phone, presence: true, format: {
    with: /\(\+[0-9]{2}\) [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}|\(\+[0-9]{2}\) [0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9]{2}/
  }
  validates :address, presence: true
  validates :user, presence: true

  accepts_nested_attributes_for :credit_card

  def email_check
    EmailCheck.find_by(email: email)
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  include CreditCardValidable

  validates :contact, presence: true
  validates :number, presence: true
  validates :franchise, presence: true

  has_one :contact
end

app/models/email_check.rb
class EmailCheck < ApplicationRecord
  validates :email, presence: true
  validates :status, presence: true

  enum status: {
    checking: 0, good: 1, bad: 2,
    catch_all: 3, unknown: 4, spamtrap: 5, abuse: 6, do_not_mail: 7,
    not_whitelisted: 8
  }

  before_validation :ensure_status

  def contacts
    Contact.where(email: email)
  end

  def register_status(status)
    raise 'Invalid status' unless status_map.key?(status)

    self.status = status_map[status]
  end

  private

  def status_map
    {
      'checking' => :checking,
      'valid' => :good,
      'invalid' => :bad,
      'catch-all' => :catch_all,
      'unknown' => :unknown,
      'spamtrap' => :spamtrap,
      'abuse' => :abuse,
      'do_not_mail' => :do_not_mail,
      'not_whitelisted' => :not_whitelisted
    }
  end

  def ensure_status
    self.status = :checking unless status
  end
end

app/models/import.rb
class Import < ApplicationRecord
  belongs_to :user
  has_many :import_contacts, dependent: :destroy
  enum status: { on_hold: 0, processing: 1, failed: 2, finished: 3 }

  validates :file, presence: true

  default_scope -> { order(:created_at) }

  before_validation :ensure_status
  after_create_commit :ensure_headers, unless: :headers
  has_one_attached :file

  def headers_valid?
    ImportContact.importable_attributes.map(&:to_s).all? do |attribute|
      headers&.any? { |_, v| v == attribute }
    end
  end

  private

  def ensure_status
    self.status = :on_hold unless status
  end

  def ensure_headers
    importer = CsvImporter.new(self)
    self.headers = importer.fetch_headers
    save
  end
end

app/models/import_contact.rb
class ImportContact < ApplicationRecord
  belongs_to :import

  scope :with_error, -> { where.not(error_message: nil) }
  scope :without_error, -> { where(error_message: nil) }

  def self.importable_attributes
    [:name, :email, :birthdate, :phone, :address, :credit_card_number]
  end

  def valid_birthdate?
    valid_formats = ['%F', '%Y%m%d']
    valid_formats.any? do |f|
      DateTime.strptime(birthdate, f)
    rescue StandardError
      false
    end
  end

  def error_hash
    JSON.parse(error_message)
  rescue JSON::ParserError
    []
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts, dependent: :destroy
  has_many :imports, dependent: :destroy
  has_many :import_contacts, through: :imports

  def token
    raise 'The user must be persisted in order to generate a JWT token' unless id

    JsonWebToken.encode(id: id)
  end

  def self.from_token(token)
    payload = JsonWebToken.decode(token)
    raise Jwt::InvalidPayload unless payload.key?('id')

    find(payload['id'])
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  include Api::V1::Concerns::Response
  include Api::V1::Concerns::ExceptionHandler

  before_action :authenticate_user!
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < Api::V1::ApiController
  skip_before_action :authenticate_user!

  def sign_up
    @user = User.create!(sign_up_params)
  end

  def sign_in
    @user = User.find_by(email: params[:email])
    return json_fail_response('Invalid email or password', :unauthorized) unless @user&.valid_password?(params[:password])
  end

  private

  def sign_up_params
    params.permit(:email, :password, :password_confirmation, :name)
  end
end

app/controllers/api/v1/concerns/exception_handler.rb
module Api::V1::Concerns::ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_fail_response('Record not found', :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_fail_response(error_data(e), :unprocessable_entity)
    end

    # TODO: Check how to rescue from a 400 Bad Request
    # rescue_from ActionController::BadRequest do |e|
    #   json_error_response(e.message, :bad_request)
    # end
  end

  private

  def error_data(error)
    error.respond_to?(:record) ? error.record.errors.messages : error.message
  end
end

app/controllers/api/v1/concerns/response.rb
module Api::V1::Concerns::Response
  def json_fail_response(data = nil, status = :bad_request)
    @data = data
    render 'api/v1/errors/fail', status: status
  end

  def json_error_response(message = nil, status = :bad_request)
    @message = message
    render 'api/v1/errors/error', status: status
  end
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < Api::V1::ApiController
  def index
    @contacts = current_user.contacts
  end
end

app/controllers/api/v1/imports_controller.rb
class Api::V1::ImportsController < Api::V1::ApiController
  before_action :set_import, only: [:show]

  def index
    @imports = current_user.imports
  end

  def show
  end

  private

  def set_import
    @import = current_user.imports.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = current_user.contacts.includes(:credit_card)
                            .paginate(page: params[:page], per_page: params[:per_page] || 5)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :assign, :execute]
  before_action :authenticate_user!

  def index
    @imports = current_user.imports
  end

  def show
    @importable_attributes = ImportContact.importable_attributes
  end

  def new
    @import = Import.new
  end

  def create
    @import = current_user.imports.create(import_params)
    if @import.valid?
      redirect_to @import, notice: 'Import was successfully created.'
    else
      render :new
    end
  end

  def assign
    @import.headers = header_params
    @import.save
    redirect_to @import
  end

  def execute
    @import.status = :processing
    @import.save

    CsvProcessJob.perform_later(@import)

    redirect_to @import
  end

  private

  def set_import
    @import = current_user.imports.find(params[:id])
  end

  def import_params
    params.require(:import).permit(:file)
  end

  def header_params
    params.require(:file_header).permit!.to_hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<% content_for :title do %>
  Contacts
<% end %>

<div class="page-header">
  <h1>Contacts</h1>
</div>

<div class="contacts table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Birthdate</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Credit card</th>
        <th>Franchise</th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <% status = contact.email_check ? contact.email_check&.status : nil %>
        <% badge = case status
                      when nil
                        'default'
                      when 'checking'
                        'info'
                      when 'good'
                        'success'
                      when 'bad'
                        'danger'
                      else
                        'warning'
                      end %>
        <tr>
          <td><%= contact.name %></td>
          <td>
            <div>
              <%= contact.email %>
            </div>
            <div class="badge badge-<%= badge %>">
              <%= (status || 'Not checked').to_s.humanize %>
            </div>
          </td>
          <td><%= contact.birthdate %></td>
          <td><%= contact.phone %></td>
          <td><%= contact.address %></td>
          <td><%= contact.credit_card.number %></td>
          <td><%= contact.credit_card.franchise %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @contacts %>

app/views/home/index.html.erb
<h1>Contact Importer</h1>
<p>This project allows you to import your contact list from a CSV file that contains dynamic header names.</p>

app/views/imports/_form.html.erb
<%= simple_form_for @import do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :enforce_import, input_html: { value: '' }, as: :hidden %>
  <div class="form-inputs">
    <%= f.input :file, as: :file, required: true, input_html: { accept:".csv" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Create Import' : 'Update Import', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/imports/index.html.erb
<% content_for :title do %>
  Imports
<% end %>

<div class="page-header">
  <h1>Imports</h1>
  <%= link_to new_import_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    New Import
  <% end %>
</div>

<div class="imports table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>File</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @imports.each do |import| %>
        <tr>
          <td>
            <%= link_to url_for(import.file).split('/').last, url_for(import.file) %>
          </td>
          <td><%= import.status.to_s.humanize %></td>
          <td>
            <%= link_to import, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/imports/new.html.erb
<% content_for :title do %>
  New Import
<% end %>

<div class="page-header">
  <h1>New Import</h1>
  <%= link_to imports_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Voltar
  <% end %>
</div>

<div class="alert alert-info">
  <strong>Don't you know what to upload?</strong>Try one of the <a href="https://github.com/seccomiro/contact-importer/tree/master/spec/fixtures/files">sample files</a>.
</div>

<%= render 'form' %>

app/views/imports/show.html.erb
<% content_for :title do %>
  Details of Import
<% end %>

<div class="page-header">
  <h1>Details of Import</h1>
  <div>
    <%= link_to imports_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Back
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>File:</dt>
  <dd>
    <%= link_to rails_blob_path(@import.file).split('/').last, url_for(@import.file) %>
  </dd>
  <dt>Status:</dt>
  <dd><%= @import.status.to_s.humanize %></dd>
</dl>

<% if @import.on_hold? %>
  <h2>Headers</h2>
  <%= form_with url: assign_import_path(@import), method: :post do |f| %>
    <div class="attributes table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Header on File</th>
            <th>System attribute</th>
          </tr>
        </thead>
        <tbody>
          <% @import.headers.each do |file_header, db_column| %>
            <tr>
              <td class="file-header"><%= file_header %></td>
              <td class="system-attribute">
                <%= f.collection_select "file_header[#{file_header}]",
                    @importable_attributes,
                    :to_s,
                    :to_s,
                    {include_blank: true, selected: db_column},
                    {class: 'form-control', id: "file_header_#{file_header}"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="form-actions">
      <%= f.submit 'Assign Attributes', class: 'btn btn-primary btn-lg' %>
      <% if @import.headers_valid? %>
        <%= link_to 'Process File', execute_import_path(@import), class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  <% end %>
<% end %>

<% if (@import.finished? || @import.failed?) && @import.import_contacts.with_error.any? %>
  <div class="failing-contacts">
    <h2>Failing Contacts</h2>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Birthdate</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Credit card</th>
            <th>Error Messages</th>
          </tr>
        </thead>
        <tbody>
          <% @import.import_contacts.with_error.each do |import_contact| %>
            <tr>
              <td><%= import_contact.name %></td>
              <td><%= import_contact.email %></td>
              <td><%= import_contact.birthdate %></td>
              <td><%= import_contact.phone %></td>
              <td><%= import_contact.address %></td>
              <td><%= import_contact.credit_card_number %></td>
              <td><%= import_contact.error_message %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + ' | ' : '' %>Contact Importer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <%= link_to 'Contact Importer', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Contacts', contacts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Import Contacts', imports_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= user_signed_in? ? current_user.email : 'Visitor' %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if user_signed_in? %>
                  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                <% else %>
                  <%= link_to 'Sign In', new_user_session_path, class: 'dropdown-item' %>
                  <%= link_to 'Sign Up', new_user_registration_path, class: 'dropdown-item' %>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
    <div class="app-toasts fixed-bottom bottom-0 end-0 p-3 d-flex justify-content-end" style="z-index: 5"></div>
  </body>
</html>